### ISSUE TITLE
[Bug]: 403 error forbidden 

### ISSUE THREAD

**Issue by sacsbrainz** [Puyodead1/udemy-downloader#92]
### What happened?

I tried to run your script on my vps but kept getting 403 error 

I used exactly same script on my physical machine it worked fine
I copied the folder to my vps am getting error

Am running an Ubuntu 20.04 with any graphical interface 

![Screenshot_20220103-173714_JuiceSSH](https://user-images.githubusercontent.com/40229306/147956183-618ec332-7122-4b65-9dab-2115a35b016e.jpg)

### Expected Result

To run without error

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

**Comment by Puyodead1** [comment]
Yeah, this is most likely related to CloudFlare captchas. There's nothing I can do right now, but I'm going to be trying a few things. Are you trying to download a course from a subscription plan?

**Comment by sacsbrainz** [comment]
> Yeah, this is most likely related to CloudFlare captchas. There's nothing I can do right now, but I'm going to be trying a few things. Are you trying to download a course from a subscription plan?

Yes i paid for the course i just need it offline

**Comment by Puyodead1** [comment]
> > Yeah, this is most likely related to CloudFlare captchas. There's nothing I can do right now, but I'm going to be trying a few things. Are you trying to download a course from a subscription plan?
> 
> Yes i paid for the course i just need it offline

No, I mean Udemy Pro/Personal plans

**Comment by sacsbrainz** [comment]
> 

Mine is a regular Udemy Marketplace course purchase 
I didn't know udemy pro was actually a real thing 😅😅

**Comment by sacsbrainz** [comment]
Also on my physical machine the course downloads are not complete some videos still didn't download
Some chapters are empty only the chapter assets where downloaded

**Comment by Puyodead1** [comment]
> Also on my physical machine the course downloads are not complete some videos still didn't download Some chapters are empty only the chapter assets where downloaded

I recommend giving the `feat-shaka` branch a try, it requires [shaka-packager](https://github.com/google/shaka-packager/releases) and is much more stable for decryption, that might solve the issue with the downloads.

**Comment by sacsbrainz** [comment]
> Yeah, this is most likely related to CloudFlare captchas. There's nothing I can do right now, but I'm going to be trying a few things. Are you trying to download a course from a subscription plan?

In regards to this try zyte proxy seems to work well witj cloudflare 
Also user agent maybe a contributing factor

**Comment by sacsbrainz** [comment]
> > Also on my physical machine the course downloads are not complete some videos still didn't download Some chapters are empty only the chapter assets where downloaded
> 
> I recommend giving the `feat-shaka` branch a try, it requires [shaka-packager](https://github.com/google/shaka-packager/releases) and is much more stable for decryption, that might solve the issue with the downloads.

Ok will try that now 
No need for cookies?

**Comment by Puyodead1** [comment]
> > > Also on my physical machine the course downloads are not complete some videos still didn't download Some chapters are empty only the chapter assets where downloaded
> > 
> > 
> > I recommend giving the `feat-shaka` branch a try, it requires [shaka-packager](https://github.com/google/shaka-packager/releases) and is much more stable for decryption, that might solve the issue with the downloads.
> 
> Ok will try that now No need for cookies?

nope, just the bearer token. cookies are only needed for subscription plans

**Comment by sacsbrainz** [comment]
On the main branch i removed the cookies i parsed and its working fine only that the encrypted files doesn't have virtual or audio 
Its just spilt into 2 different segments 
![20220104_004529](https://user-images.githubusercontent.com/40229306/147992197-6e354694-dc92-4e98-acd3-4461a8250f32.jpg)

Meanwhile the console prints out another error
![20220104_003848](https://user-images.githubusercontent.com/40229306/147992218-8ce43805-fc42-4bd7-bb14-ef7002a1723a.jpg)

**Comment by Puyodead1** [comment]
> On the main branch i removed the cookies i parsed and its working fine only that the encrypted files doesn't have visual and audio Its just spilt into 2 different segments ![20220104_004529](https://user-images.githubusercontent.com/40229306/147992197-6e354694-dc92-4e98-acd3-4461a8250f32.jpg)
> 
> Meanwhile the console prints out another error ![20220104_003848](https://user-images.githubusercontent.com/40229306/147992218-8ce43805-fc42-4bd7-bb14-ef7002a1723a.jpg)

you didnt put the key and key id in the keyfile.json or you didnt put it in correctly
```json
{
"key id goes here": "key goes here"
}

**Comment by sacsbrainz** [comment]
> > On the main branch i removed the cookies i parsed and its working fine only that the encrypted files doesn't have visual and audio Its just spilt into 2 different segments ![20220104_004529](https://user-images.githubusercontent.com/40229306/147992197-6e354694-dc92-4e98-acd3-4461a8250f32.jpg)
> > Meanwhile the console prints out another error ![20220104_003848](https://user-images.githubusercontent.com/40229306/147992218-8ce43805-fc42-4bd7-bb14-ef7002a1723a.jpg)
> 
> you didnt put the key and key id in the keyfile.json or you didnt put it in correctly, it cant decrypt the files since it cant get the key for it
> 
> ```json
> {
> "key id goes here": "key goes here"
> }
> ```

I did

**Comment by sacsbrainz** [comment]
Or does is change?

**Comment by Puyodead1** [comment]
it changes for each course

**Comment by sacsbrainz** [comment]
> it changes for each course

So error course has its own different key?

**Comment by Puyodead1** [comment]
> > it changes for each course
> 
> So every course has its own different key?

yes, usually its every video but udemy decided to do every course

**Comment by sacsbrainz** [comment]
> > > it changes for each course
> > 
> > 
> > So every course has its own different key?
> 
> yes, usually its every video but udemy decided to do every course

Ok thanks will generate again thanks

Thank God is it not every video 🤣

**Comment by sacsbrainz** [comment]
Its working fine now
Thanks

**Comment by Samhunter91** [comment]
> Yeah, this is most likely related to CloudFlare captchas. There's nothing I can do right now, but I'm going to be trying a few things. Are you trying to download a course from a subscription plan?

I am downloading using the personal plan ,is there any work around of this 404 forbidden error?

**Comment by Puyodead1** [comment]
> > Yeah, this is most likely related to CloudFlare captchas. There's nothing I can do right now, but I'm going to be trying a few things. Are you trying to download a course from a subscription plan?
> 
> I am downloading using the personal plan ,is there any work around of this 403 forbidden error?

I'm working on rewriting the way personal plan works that seems to bypass the captchas, but theres nothing that i know of that you can do until i can finish this update. I have to rewrite a good portion of the code to use browser automation

**Comment by Samhunter91** [comment]
> 

If you need the personal plan subscription account I can share it with you ,if it helps in the process

**Comment by Puyodead1** [comment]
> > 
> 
> If you need the personal plan subscription account I can share it with you ,if it helps in the process

Thank you for the offer, someone else already lent me one :)

I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium

There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it

**Comment by Samhunter91** [comment]
> > > 
> > 
> > 
> > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> 
> Thank you for the offer, someone else already lent me one :)
> 
> I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> 
> There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> 
> Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.

Thank you,I will try it today and let you know if I ran into some problem.

**Comment by Samhunter91** [comment]
> > > 
> > 
> > 
> > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> 
> Thank you for the offer, someone else already lent me one :)
> 
> I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> 
> There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> 
> Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.

I tried it and it works 😍,but I had to add the bearer token , username and password while the time of execution ,adding the bearer token, username and password in config.toml file but at the while executing it ask again for all this ,is is the only problem I faced but everything is fine .

**Comment by Samhunter91** [comment]
> > > 
> > 
> > 
> > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> 
> Thank you for the offer, someone else already lent me one :)
> 
> I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> 
> There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> 
> Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.

And yes The captions are also not downloading ,assets are downloading fine but captions are not downloading 
I have added --download-captions

**Comment by Samhunter91** [comment]
> > > 
> > 
> > 
> > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> 
> Thank you for the offer, someone else already lent me one :)
> 
> I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> 
> There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> 
> Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.

Everything is working fine but the captions are still not working I had disabled the download-captions and download-assets  and keep-vtt by including # infront of them ,I simply use main.py -c 'courselink' -sc --download-captions --download-assets but still captions are not downloading and assets are downloading fine ,
It is some problem with the captions 
I hope you will fix this

**Comment by Puyodead1** [comment]
> > > > 
> > > 
> > > 
> > > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> > 
> > 
> > Thank you for the offer, someone else already lent me one :)
> > I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> > There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> > Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.
> 
> Everything is working fine but the captions are still not working I had disabled the download-captions and download-assets and keep-vtt by including # infront of them ,I simply use main.py -c 'courselink' -sc --download-captions --download-assets but still captions are not downloading and assets are downloading fine , It is some problem with the captions I hope you will fix this

I just updated the selenium branch to include the fix for this from master

**Comment by Samhunter91** [comment]
> > > > > 
> > > > 
> > > > 
> > > > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> > > 
> > > 
> > > Thank you for the offer, someone else already lent me one :)
> > > I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> > > There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> > > Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.
> > 
> > 
> > Everything is working fine but the captions are still not working I had disabled the download-captions and download-assets and keep-vtt by including # infront of them ,I simply use main.py -c 'courselink' -sc --download-captions --download-assets but still captions are not downloading and assets are downloading fine , It is some problem with the captions I hope you will fix this
> 
> I just updated the selenium branch to include the fix for this from master



> > > > 
> > > 
> > > 
> > > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> > 
> > 
> > Thank you for the offer, someone else already lent me one :)
> > I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> > There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> > Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.
> 
> Thank you,I will try it today and let you know if I ran into some problem.

![Screenshot 2022-01-10 191200](https://user-images.githubusercontent.com/88492275/148825732-018cc3b5-1a12-41ac-ab69-a94a886cf3bc.png)
![Screenshot 2022-01-10 191313](https://user-images.githubusercontent.com/88492275/148825737-3d6d2569-c8f0-4cb0-822b-2ce4e80c61cc.png)

I am getting this error now 
I have already installed the requirements.txt modules

**Comment by Samhunter91** [comment]
> > > > > 
> > > > 
> > > > 
> > > > If you need the personal plan subscription account I can share it with you ,if it helps in the process
> > > 
> > > 
> > > Thank you for the offer, someone else already lent me one :)
> > > I have published an experimental branch that should bypass cloudflare captchas: https://github.com/Puyodead1/udemy-downloader/tree/feat-selenium
> > > There's new requirements so be sure to `pip install -r requirements.txt`, edit the config.toml file (at least just update the selenium section with username and password), and make sure you have chrome installed. If you have any troubles setting this up, please let me know so I can assist and add better documentation for it
> > > Edit: Forgot to mention you will also need to specify `-sc` now to tell the program its a subscription based course.
> > 
> > 
> > Everything is working fine but the captions are still not working I had disabled the download-captions and download-assets and keep-vtt by including # infront of them ,I simply use main.py -c 'courselink' -sc --download-captions --download-assets but still captions are not downloading and assets are downloading fine , It is some problem with the captions I hope you will fix this
> 
> I just updated the selenium branch to include the fix for this from master

![Screenshot 2022-01-10 191200](https://user-images.githubusercontent.com/88492275/148869847-525d3416-0341-4962-adaa-d9151256a1e9.png)
![Screenshot 2022-01-10 191313](https://user-images.githubusercontent.com/88492275/148869852-cd8b8fff-9b5a-4d60-820c-feb8a6f5a5c5.png)

I am getting this error now
I have already installed the requirements.txt modules

**Comment by Puyodead1** [comment]
I'm going to assume this is because the course is "large", which i haven't implement support for yet. Do you know how many hours the course is?

**Comment by Samhunter91** [comment]
> I'm going to assume this is because the course is "large", which i haven't implement support for yet. Do you know how many hours the course is?

It is 2.5 hours course ,name of the course is How to Draw Cute Cartoon Characters.

**Comment by Puyodead1** [comment]
Ah, I see the issue. There's an invalid utf-8 character. I'll have to add sanitation to the strings.
Somewhere on the page, there's a `“` (Double Left Quotation Mark) which is an invalid utf-8 character compared to `"`

**Comment by Samhunter91** [comment]
> Ah, I see the issue. There's an invalid utf-8 character. I'll have to add sanitation to the strings. Somewhere on the page, there's a `“` (Double Left Quotation Mark) which is an invalid utf-8 character compared to `"`

So ,have you fixed this issue?

**Comment by Puyodead1** [comment]
> > Ah, I see the issue. There's an invalid utf-8 character. I'll have to add sanitation to the strings. Somewhere on the page, there's a `“` (Double Left Quotation Mark) which is an invalid utf-8 character compared to `"`
> 
> 
> 
> So ,have you fixed this issue?

No, I was sleeping. I'll fix it in a little bit

**Comment by Puyodead1** [comment]
> > Ah, I see the issue. There's an invalid utf-8 character. I'll have to add sanitation to the strings. Somewhere on the page, there's a `“` (Double Left Quotation Mark) which is an invalid utf-8 character compared to `"`
> 
> So ,have you fixed this issue?

Could you check something on your system for me please? Open a python terminal (should be able to search for python in the windows search and open `Python (command line)`, or open cmd/powershell and just type `python`) and paste this:
```py
import sys
import locale

sys.getfilesystemencoding()
locale.getpreferredencoding()
```
This will output your systems encoding, which may be set to the wrong thing.

**Comment by Samhunter91** [comment]
> 

This was the output
![Screenshot 2022-01-12 081139](https://user-images.githubusercontent.com/88492275/149089014-48f8cf62-7f04-47cd-9ace-767e53c24cca.png)


And tried the latest selenium branch and  I tried to download another course which 27.5 hours and captions and assets are downloading fine but some videos are skipped 
Here is the error screenshot 
![IMG_20220112_134225](https://user-images.githubusercontent.com/88492275/149089362-889a04f3-916f-4dd0-8d5e-61e572462688.jpg)

I also tried the previous 2.5 hours course and everything went smooth in that course every captions and assets are downloaded with all video files, don't know what happened while downloading the other one 

Here is name of the other course 
Complete Ethical Hacking Bootcamp 2022: Zero to Mastery

**Comment by Samhunter91** [comment]
> > > Ah, I see the issue. There's an invalid utf-8 character. I'll have to add sanitation to the strings. Somewhere on the page, there's a `“` (Double Left Quotation Mark) which is an invalid utf-8 character compared to `"`
> > 
> > 
> > So ,have you fixed this issue?
> 
> Could you check something on your system for me please? Open a python terminal (should be able to search for python in the windows search and open `Python (command line)`, or open cmd/powershell and just type `python`) and paste this:
> 
> ```python
> import sys
> import locale
> 
> sys.getfilesystemencoding()
> locale.getpreferredencoding()
> ```
> 
> This will output your systems encoding, which may be set to the wrong thing.

> 

This was the output
![Screenshot 2022-01-12 081139](https://user-images.githubusercontent.com/88492275/149089014-48f8cf62-7f04-47cd-9ace-767e53c24cca.png)


And tried the latest selenium branch and  I tried to download another course which 27.5 hours and captions and assets are downloading fine but some videos are skipped 
Here is the error screenshot 
![IMG_20220112_134225](https://user-images.githubusercontent.com/88492275/149089362-889a04f3-916f-4dd0-8d5e-61e572462688.jpg)

I also tried the previous 2.5 hours course and everything went smooth in that course every captions and assets are downloaded with all video files, don't know what happened while downloading the other one 

Here is name of the other course 
Complete Ethical Hacking Bootcamp 2022: Zero to Mastery

**Comment by sacsbrainz** [comment]
Please read my email

**Comment by Samhunter91** [comment]
> > > > > Ah, I see the issue. There's an invalid utf-8 character. I'll have to add sanitation to the strings. Somewhere on the page, there's a `“` (Double Left Quotation Mark) which is an invalid utf-8 character compared to `"`
> > > > 
> > > > 
> > > > So ,have you fixed this issue?
> > > 
> > > 
> > > Could you check something on your system for me please? Open a python terminal (should be able to search for python in the windows search and open `Python (command line)`, or open cmd/powershell and just type `python`) and paste this:
> > > ```python
> > > import sys
> > > import locale
> > > 
> > > sys.getfilesystemencoding()
> > > locale.getpreferredencoding()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will output your systems encoding, which may be set to the wrong thing.
> > 
> > 
> > > 
> > 
> > 
> > This was the output ![Screenshot 2022-01-12 081139](https://user-images.githubusercontent.com/88492275/149089014-48f8cf62-7f04-47cd-9ace-767e53c24cca.png)
> > And tried the latest selenium branch and I tried to download another course which 27.5 hours and captions and assets are downloading fine but some videos are skipped Here is the error screenshot ![IMG_20220112_134225](https://user-images.githubusercontent.com/88492275/149089362-889a04f3-916f-4dd0-8d5e-61e572462688.jpg)
> > I also tried the previous 2.5 hours course and everything went smooth in that course every captions and assets are downloaded with all video files, don't know what happened while downloading the other one
> > Here is name of the other course Complete Ethical Hacking Bootcamp 2022: Zero to Mastery
> 
> Hm, okay.
> 
> This error is caused by the path length being too long, I recommend moving the `udemy-downloader-feat-selenium` folder into the `Downloads` folder and deleting `udemy-downloader-feat-selenium (2)`, then use `--id-as-course-name`.
> 
> As far as the other course, I might need an account to test with as I'm not 100% sure where the problem actually comes from, if you're willing to provide an account, you can email me at [puyodead@protonmail.com](mailto:puyodead@protonmail.com)

I have sent you the account credentials

**Comment by Puyodead1** [comment]
I've tested the draw-cute-characters course and its downloading without issue. Please update the the latest version of the selenium branch and try it

**Comment by Samhunter91** [comment]
> I've tested the draw-cute-characters course and its downloading without issue. Please update the the latest version of the selenium branch and try it

I am having some issue with decryption ,some of the files are not decrypting property

**Comment by Puyodead1** [comment]
the feat-shaka branch has now been deleted, and shaka-packager is now in the master branch, there is also some bug fixes that address issues with decryption on some files that contain commas in the filename resulting in decryption failure. The master branch also includes much better debug logging now to print the output from the external programs to find errors easier.

**Comment by Samhunter91** [comment]
> the feat-shaka branch has now been deleted, and shaka-packager is now in the master branch, there is also some bug fixes that address issues with decryption on some files that contain commas in the filename resulting in decryption failure. The master branch also includes much better debug logging now to print the output from the external programs to find errors easier.

My subscription was over so I didn't got a chance to try it ,I will make a new account and try it . Thanks

**Comment by Samhunter91** [comment]
> the feat-shaka branch has now been deleted, and shaka-packager is now in the master branch, there is also some bug fixes that address issues with decryption on some files that contain commas in the filename resulting in decryption failure. The master branch also includes much better debug logging now to print the output from the external programs to find errors easier.

Guess now I can't download any course as the method I was relying on to get the keys is patched 😪

**Comment by krishnastunning** [comment]
> Its working fine now Thanks

bro can you help me to find Decryption Key ID Decryption Key

**Comment by sacsbrainz** [comment]
No

**Comment by sbchaudhari077** [comment]
> > > > it changes for each course
> > > 
> > > 
> > > So every course has its own different key?
> > 
> > 
> > yes, usually its every video but udemy decided to do every course
> 
> Ok thanks will generate again thanks
> 
> Thank God is it not every video 🤣

Hi, Can you please guide me on how to get KeyID and Key for Udemy Course?
